In [68]:
pip show numpy

Name: numpy
Version: 1.26.0
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
        All rights reserved.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are
        met:
        
            * Redistributions of source code must retain the above copyright
               notice, this list of conditions and the following disclaimer.
        
            * Redistributions in binary form must reproduce the above
               copyright notice, this list of conditions and the following
               disclaimer in the documentation and/or other materials provided
               with the distribution.
        
            * Neither the name of the NumPy Developers nor the names of any
               contributors may be used to endorse or promo

In [69]:
import numpy as np
print(np.__version__)

1.26.0


In [70]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [71]:
print (a[0])
print (a[0][1])
print (a[1][1])

[1 2 3]
2
5


In [72]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [73]:
a.ndim

2

In [74]:
a = np.array([[[1,2,3],[4,5,6]], [[1,3,5],[2,4,6]]])
a.shape

(2, 2, 3)

In [75]:
a.ndim

3

In [76]:
a.size

12

In [77]:
a.dtype

dtype('int32')

In [78]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a.reshape(-1,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
# a.reshape(2, 3)
a.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
a.reshape(2,2,-1) # -1 lets NumPy automatically calculate the remaining dimensions

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [81]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
a = np.array([[[1,2,3],[4,5,6]], [[1,3,5],[2,4,6]]])
a.flatten()

array([1, 2, 3, 4, 5, 6, 1, 3, 5, 2, 4, 6])

In [83]:
# a = np.array([[1, 2, 3, 4],[5, 6, 7, "8"]], dtype=float)
a = np.array([[1, 2, 3, 4.3],[5, 6, 7, "8"]], dtype=int)
# 자동으로 형변환을 지원한다.
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
a.dtype

dtype('int32')

In [85]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.arange(-3, 3) # default step size is 1

array([-3, -2, -1,  0,  1,  2])

In [87]:
np.arange(-5, 5, 2)

array([-5, -3, -1,  1,  3])

In [88]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [89]:
print(range(0, 5, 0.5))
# 기본 내장함수 range는 정수형만 지원함

TypeError: 'float' object cannot be interpreted as an integer

In [90]:
for x in range(0, 5, 1):
  print(x)

0
1
2
3
4


In [91]:
np.ones(shape=(3,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [92]:
np.zeros(shape=(2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [93]:
np.empty(shape=(2,4), dtype=np.float32) # values may change every time

array([[ 0.0000000e+00,  0.0000000e+00, -2.6476696e-23,  5.9695315e-43],
       [-2.6480483e-23,  5.9695315e-43, -2.6478463e-23,  5.9695315e-43]],
      dtype=float32)

In [94]:
np.identity(n=3) # default type is float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
np.eye(N=2, M=4) # default type is float

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [96]:
np.eye(N=3, M=5, k=2, dtype=int)
# k determines the starting index of diagonal

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [97]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
np.diag(a)
# array의 대각성분을 얻음

array([ 0,  5, 10, 15])

In [99]:
np.diag(a, k=1)
 # values may change every time

array([ 1,  6, 11])

In [100]:
np.diag(a, k=-2)

array([ 8, 13])

In [101]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
print(np.diag(b))
print(np.diag(b, k=1))
# dimension이 1인 경우에는 입력된 list를 대각성분으로 갖는 (n, n)의 list를 반환함


[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 0 9]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [103]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a[0]

array([1, 2, 3, 4])

In [104]:
a[1,2] # [row index, column index]

7

In [105]:
a[0, 2] = 10 # values may be altered using indexing
a

array([[ 1,  2, 10,  4],
       [ 5,  6,  7,  8]])

In [106]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a[1:] # rows 1 to the end, all columns

array([[5, 6, 7, 8]])

In [107]:
a[ : , 2: ] # all rows, columns from 2 to the end

array([[3, 4],
       [7, 8]])

In [108]:
a[1: , 1:3] # rows 1 to the end, columns 1 and 2

array([[6, 7]])

In [109]:
a[1: , 1:4] # rows 1 to the end, columns 1 and 2

array([[6, 7, 8]])

In [110]:
a[::2, ::3] # every second row, every third column beginning at the first row/column

array([[1, 4]])

In [111]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
a.sum() # sum of all elements

78

In [113]:
a.sum(axis=0) # sum of each column’s elements

array([15, 18, 21, 24])

In [114]:
a.sum(axis=1) # sum of each row’s elements

array([10, 26, 42])

In [115]:
a.mean() # mean of all elements

6.5

In [116]:
a.mean(axis=0) # mean of each column’s elements

array([5., 6., 7., 8.])

In [117]:
a.mean(axis=1) # mean of each row’s elements

array([ 2.5,  6.5, 10.5])

In [118]:
a.std() # standard deviation of all elements

3.452052529534663

In [119]:
a.std(axis=0) # std of each column’s elements

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [120]:
a.std(axis=1) # std of each row’s elements

array([1.11803399, 1.11803399, 1.11803399])

In [122]:
a = np.arange(1, 9).reshape(2,2,-1)
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [123]:
a.sum(axis=0)

array([[ 6,  8],
       [10, 12]])