In [78]:
import numpy as np

In [79]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [81]:
a = np.array([1, 2, 3, 4]).reshape(2,2)
b = np.array([[5],[6]])
print(a, '\n')
print(b)
np.concatenate((a, b), axis=1)

[[1 2]
 [3 4]] 

[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [82]:
a = np.array([1, 2, 3, 4]).reshape(2,2)
b = np.array([[5],[6]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [83]:
a = np.array([1, 2, 3, 4]).reshape(2,2)
b = np.array([[5,1],[6,1]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 1],
       [6, 1]])

In [123]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([[8,7,6,5], [4,3,2,1],])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [124]:
print(a + b)

[[9 9 9 9]
 [9 9 9 9]]


In [125]:
print(a - b)

[[-7 -5 -3 -1]
 [ 1  3  5  7]]


In [126]:
print(a / b)

[[0.125      0.28571429 0.5        0.8       ]
 [1.25       2.         3.5        8.        ]]


In [127]:
print(a * b)

[[ 8 14 18 20]
 [20 18 14  8]]


In [128]:
print(a ** b)

[[   1  128  729 1024]
 [ 625  216   49    8]]


In [130]:
a = np.arange(1,4)
b = np.arange(5,20,5).reshape(3,-1)
# a.dot(b)
a@b

array([70])

In [91]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(5,35,5).reshape(3,-1)
a.dot(b)

array([[110, 140],
       [245, 320]])

In [92]:
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [94]:
b = np.arange(5, 20, 5)
b

array([ 5, 10, 15])

In [95]:
a + b

array([[ 6, 12, 18],
       [ 9, 15, 21],
       [12, 18, 24]])

In [96]:
a * b

array([[  5,  20,  45],
       [ 20,  50,  90],
       [ 35,  80, 135]])

In [97]:
a = np.array([3,7,1])
b = np.array([5,5,5])
a > b

array([False,  True, False])

In [98]:
a = np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
a > 5

array([False, False, False, False, False,  True,  True,  True])

In [100]:
import numpy as np
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [101]:
np.where(a > 5)

(array([3, 4], dtype=int64),)

In [102]:
np.where(a > 2)

(array([1, 2, 3, 4], dtype=int64),)

In [103]:
np.where(a > 5, 'T', 'F')
# np.where(a > 5, 1, 0)

array(['F', 'F', 'F', 'T', 'T'], dtype='<U1')

In [104]:
a = np.array([3,7,1,5])
a

array([3, 7, 1, 5])

In [105]:
np.sort(a)

array([1, 3, 5, 7])

In [106]:
a

array([3, 7, 1, 5])

In [107]:
np.sort(a)[::-1]

array([7, 5, 3, 1])

In [108]:
a[::-1]

array([5, 1, 7, 3])

In [109]:
pip show pandas

Name: pandas
Version: 2.2.1
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License
        
        Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
        All rights reserved.
        
        Copyright (c) 2011-2023, Open source contributors.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials 

In [110]:
import pandas as pd
print(pd.__version__)

2.2.1


In [111]:
import numpy as np
titanic_df = pd.read_csv("./data/w5/train.csv")

https://gooopy.tistory.com/79

In [112]:
titanic_df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [113]:
titanic_df.shape

(891, 12)

In [114]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [115]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [116]:
titanic_df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [117]:
titanic_df['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [118]:
type(titanic_df['Survived'])

pandas.core.series.Series

In [119]:
titanic_df[titanic_df['Age'] > 50].head(5)

PassengerId  Survived  Pclass                              Name     Sex  \
6             7         0       1           McCarthy, Mr. Timothy J    male   
11           12         1       1          Bonnell, Miss. Elizabeth  female   
15           16         1       2  Hewlett, Mrs. (Mary D Kingcome)   female   
33           34         0       2             Wheadon, Mr. Edward H    male   
54           55         0       1    Ostby, Mr. Engelhart Cornelius    male   

     Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
6   54.0      0      0       17463  51.8625   E46        S  
11  58.0      0      0      113783  26.5500  C103        S  
15  55.0      0      0      248706  16.0000   NaN        S  
33  66.0      0      0  C.A. 24579  10.5000   NaN        S  
54  65.0      0      1      113509  61.9792   B30        C

In [120]:
titanic_df.loc[titanic_df['Age'] > 50,['Name','Age','Sex']].head(5)

Name   Age     Sex
6            McCarthy, Mr. Timothy J  54.0    male
11          Bonnell, Miss. Elizabeth  58.0  female
15  Hewlett, Mrs. (Mary D Kingcome)   55.0  female
33             Wheadon, Mr. Edward H  66.0    male
54    Ostby, Mr. Engelhart Cornelius  65.0    male

In [121]:
df1 = pd.DataFrame({'ID':[1,2,3], 'Name':['A','B','C']})
df2 = pd.DataFrame({'ID':[2,3,4], 'Age':[25,30,22]})

In [122]:
pd.merge(df1, df2, how='cross')

ID_x Name  ID_y  Age
0     1    A     2   25
1     1    A     3   30
2     1    A     4   22
3     2    B     2   25
4     2    B     3   30
5     2    B     4   22
6     3    C     2   25
7     3    C     3   30
8     3    C     4   22