In [1]:
pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, bqplot, chex, cmdstanpy, contourpy, cufflinks, cupy-cuda12x, cvxpy, datascience, db-dtypes, dopamine-rl, ecos, flax, folium, geemap, gensim, gym, h5py, holoviews, hyperopt, ibis-framework, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, scikit-image, scikit-learn, scipy, scs, seaborn, shapely, sklearn

In [2]:
import numpy as np
print(np.__version__)

1.25.2


In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [4]:
print (a[0])
print (a[0][1])
print (a[1][1])

[1 2 3]
2
5


In [5]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [6]:
a.ndim

2

In [7]:
a = np.array([[[1,2,3],[4,5,6]], [[1,3,5],[2,4,6]]])
a.shape

(2, 2, 3)

In [8]:
a.ndim

3

In [9]:
a.size

12

In [10]:
a.dtype

dtype('int64')

In [11]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a.reshape(-1,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a.reshape(2, 3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [13]:
a.reshape(2,2,-1) # -1 lets NumPy automatically calculate the remaining dimensions

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a = np.array([[[1,2,3],[4,5,6]], [[1,3,5],[2,4,6]]])
a.flatten()

array([1, 2, 3, 4, 5, 6, 1, 3, 5, 2, 4, 6])

In [16]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, "8"]], dtype=float)
a

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [17]:
a.dtype

dtype('float64')

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(-3, 3) # default step size is 1

array([-3, -2, -1,  0,  1,  2])

In [20]:
np.arange(-5, 5, 2)

array([-5, -3, -1,  1,  3])

In [21]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [22]:
print(range(0, 5, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [23]:
for x in range(0, 5, 1):
  print(x)

0
1
2
3
4


In [24]:
np.ones(shape=(3,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [25]:
np.zeros(shape=(2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [26]:
np.empty(shape=(2,4), dtype=np.float32) # values may change every time

array([[6.1659720e+32, 3.3370522e-41, 0.0000000e+00, 0.0000000e+00],
       [3.1199177e-10, 4.4220776e-41, 1.6460746e-25, 4.4220776e-41]],
      dtype=float32)

In [27]:
np.identity(n=3) # default type is float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(N=2, M=4) # default type is float

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [29]:
np.eye(N=3, M=5, k=2, dtype=int)
# k determines the starting index of diagonal

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
np.diag(a)

array([ 0,  5, 10, 15])

In [32]:
np.diag(a, k=1)
 # values may change every time

array([ 1,  6, 11])

In [33]:
np.diag(a, k=-2)

array([ 8, 13])

In [34]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.diag(b)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [36]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a[0]

array([1, 2, 3, 4])

In [37]:
a[1,2] # [row index, column index]

7

In [38]:
a[0, 2] = 10 # values may be altered using indexing
a

array([[ 1,  2, 10,  4],
       [ 5,  6,  7,  8]])

In [39]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a[1:] # rows 1 to the end, all columns

array([[5, 6, 7, 8]])

In [40]:
a[ : , 2: ] # all rows, columns from 2 to the end

array([[3, 4],
       [7, 8]])

In [41]:
a[1: , 1:3] # rows 1 to the end, columns 1 and 2

array([[6, 7]])

In [42]:
a[1: , 1:4] # rows 1 to the end, columns 1 and 2

array([[6, 7, 8]])

In [43]:
a[::2, ::3] # every second row, every third column beginning at the first row/column

array([[1, 4]])

In [2]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a.sum() # sum of all elements

78

In [46]:
a.sum(axis=0) # sum of each column’s elements

array([15, 18, 21, 24])

In [47]:
a.sum(axis=1) # sum of each row’s elements

array([10, 26, 42])

In [3]:
a.mean() # mean of all elements

6.5

In [4]:
a.mean(axis=0) # mean of each column’s elements

array([5., 6., 7., 8.])

In [5]:
a.mean(axis=1) # mean of each row’s elements

array([ 2.5,  6.5, 10.5])

In [6]:
a.std() # standard deviation of all elements

3.452052529534663

In [7]:
a.std(axis=0) # std of each column’s elements

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [8]:
a.std(axis=1) # std of each row’s elements

array([1.11803399, 1.11803399, 1.11803399])

In [48]:
a = np.arange(1, 9).reshape(2,2,-1)
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a.sum(axis=0)